version: '3'

services:
    db:
        image: onjin/alpine-postgres
        environment:
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
        ports: 
        - "5432:5432"

    # redis:
    #     image: redis:5-alpine
    #     ports: [6379]

    # rabbitmq:
    #     image: rabbitmq:3.7-management
    #     ports: [5672, 15672]

    # mailcatcher:
    #     image: schickling/mailcatcher
    #     ports: [1025, 1080]

    php-fpm:
        build:
            context: ./php-fpm
        depends_on:
        - db
        environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}?serverVersion=11&charset=utf8
        volumes:
        - ../src:/var/www
    
    nginx:
        build:
           context: ./nginx
        volumes:
        - ../src:/var/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/sites/:/etc/nginx/sites-available
        - ./nginx/conf.d/:/etc/nginx/conf.d
        - ./logs:/var/log
        depends_on:
        - php-fpm
        ports:
        - "8080:80"
        - "443:443"